#!name=[直连/无节点可用]LimbusCompany IOS Localization
#!desc=[不保证高可用性]边狱巴士ios汉化模块 by ghcruise
#!arguments=api_cdn_ip:13.33.183.110
#!arguments-desc=api_cdn_ip:Amazon Cloudfront优选IP

[Host]
securetoken.googleapis.com = 172.98.12.23
firebaselogging-pa.googleapis.com = 172.98.12.23
battlelog.limbuscompanyapi.com = {{{api_cdn_ip}}}
www.limbuscompanyapi.com = {{{api_cdn_ip}}}
presence.limbuscompanyapi.com = {{{api_cdn_ip}}}

[Rule]
IP-CIDR,172.98.12.23/32,DIRECT
IP-CIDR,{{{api_cdn_ip}}}/32,DIRECT
DOMAIN,securetoken.googleapis.com,DIRECT
DOMAIN,firebaselogging-pa.googleapis.com,DIRECT
DOMAIN,battlelog.limbuscompanyapi.com,DIRECT
DOMAIN,www.limbuscompanyapi.com,DIRECT
DOMAIN,presence.limbuscompanyapi.com,DIRECT
DOMAIN-SUFFIX,unity3d.com,DIRECT

[URL Rewrite]
^https?://.*localize_jp.zip$ https://limbus-download.voidfissure.de/download/localize_jp.zip 302

^https://downloadcommon\.limbuscompanycdn\.org/.*LocalizePatchInfo\.json$ https://limbus-download.voidfissure.de/download/manifest.json 302

[MITM]
hostname = %APPEND% *.limbuscompanycdn.org